name: Outputs Example

on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "::set-output name=location::california"
      - id: step2
        run: echo 'sacramento is a city in ${{ steps.step1.outputs.location }}'
